import { ICountry } from '@type/word.types';

export const AFRICA = {
  dza: {
    flag: 'dz',
    name: 'Algeria',
    prefix: '+213',
    continent: 'africa',
    region: 'africa',
  },
  ago: {
    flag: 'ao',
    name: 'Angola',
    prefix: '+244',
    continent: 'africa',
    region: 'africa',
  },
  ben: {
    flag: 'bj',
    name: 'Benin',
    prefix: '+229',
    continent: 'africa',
    region: 'africa',
  },
  bwa: {
    flag: 'bw',
    name: 'Botswana',
    prefix: '+267',
    continent: 'africa',
    region: 'africa',
  },
  bfa: {
    flag: 'bf',
    name: 'Burkina Faso',
    prefix: '+226',
    continent: 'africa',
    region: 'africa',
  },
  bdi: {
    flag: 'bi',
    name: 'Burundi',
    prefix: '+257',
    continent: 'africa',
    region: 'africa',
  },
  cpv: {
    flag: 'cv',
    name: 'Cabo Verde',
    prefix: '+238',
    continent: 'africa',
    region: 'africa',
  },
  cmr: {
    flag: 'cm',
    name: 'Cameroon',
    prefix: '+237',
    continent: 'africa',
    region: 'africa',
  },
  caf: {
    flag: 'cf',
    name: 'Central African Republic',
    prefix: '+236',
    continent: 'africa',
    region: 'africa',
  },
  tcd: {
    flag: 'td',
    name: 'Chad',
    prefix: '+235',
    continent: 'africa',
    region: 'africa',
  },
  com: {
    flag: 'km',
    name: 'Comoros',
    prefix: '+269',
    continent: 'africa',
    region: 'africa',
  },
  cog: {
    flag: 'cg',
    name: 'Republic of the Congo',
    prefix: '+242',
    continent: 'africa',
    region: 'africa',
  },
  cod: {
    flag: 'cd',
    name: 'Democratic Republic of the Congo',
    prefix: '+243',
    continent: 'africa',
    region: 'africa',
  },
  civ: {
    flag: 'ci',
    name: "Côte d'Ivoire",
    prefix: '+225',
    continent: 'africa',
    region: 'africa',
  },
  dji: {
    flag: 'dj',
    name: 'Djibouti',
    prefix: '+253',
    continent: 'africa',
    region: 'africa',
  },
  egy: {
    flag: 'eg',
    name: 'Egypt',
    prefix: '+20',
    continent: 'africa',
    region: 'africa',
  },
  gnq: {
    flag: 'gq',
    name: 'Equatorial Guinea',
    prefix: '+240',
    continent: 'africa',
    region: 'africa',
  },
  eri: {
    flag: 'er',
    name: 'Eritrea',
    prefix: '+291',
    continent: 'africa',
    region: 'africa',
  },
  swz: {
    flag: 'sz',
    name: 'Eswatini',
    prefix: '+268',
    continent: 'africa',
    region: 'africa',
  },
  eth: {
    flag: 'et',
    name: 'Ethiopia',
    prefix: '+251',
    continent: 'africa',
    region: 'africa',
  },
  gab: {
    flag: 'ga',
    name: 'Gabon',
    prefix: '+241',
    continent: 'africa',
    region: 'africa',
  },
  gmb: {
    flag: 'gm',
    name: 'The Gambia',
    prefix: '+220',
    continent: 'africa',
    region: 'africa',
  },
  gha: {
    flag: 'gh',
    name: 'Ghana',
    prefix: '+233',
    continent: 'africa',
    region: 'africa',
  },
  gin: {
    flag: 'gn',
    name: 'Guinea',
    prefix: '+224',
    continent: 'africa',
    region: 'africa',
  },
  gnb: {
    flag: 'gw',
    name: 'Guinea-Bissau',
    prefix: '+245',
    continent: 'africa',
    region: 'africa',
  },
  ken: {
    flag: 'ke',
    name: 'Kenya',
    prefix: '+254',
    continent: 'africa',
    region: 'africa',
  },
  lso: {
    flag: 'ls',
    name: 'Lesotho',
    prefix: '+266',
    continent: 'africa',
    region: 'africa',
  },
  lbr: {
    flag: 'lr',
    name: 'Liberia',
    prefix: '+231',
    continent: 'africa',
    region: 'africa',
  },
  lby: {
    flag: 'ly',
    name: 'Libya',
    prefix: '+218',
    continent: 'africa',
    region: 'africa',
  },
  mdg: {
    flag: 'mg',
    name: 'Madagascar',
    prefix: '+261',
    continent: 'africa',
    region: 'africa',
  },
  mwi: {
    flag: 'mw',
    name: 'Malawi',
    prefix: '+265',
    continent: 'africa',
    region: 'africa',
  },
  mli: {
    flag: 'ml',
    name: 'Mali',
    prefix: '+223',
    continent: 'africa',
    region: 'africa',
  },
  mrt: {
    flag: 'mr',
    name: 'Mauritania',
    prefix: '+222',
    continent: 'africa',
    region: 'africa',
  },
  mus: {
    flag: 'mu',
    name: 'Mauritius',
    prefix: '+230',
    continent: 'africa',
    region: 'africa',
  },
  myt: {
    flag: 'yt',
    name: 'Mayotte',
    prefix: '+262',
    continent: 'africa',
    region: 'africa',
  },
  mar: {
    flag: 'ma',
    name: 'Morocco',
    prefix: '+212',
    continent: 'africa',
    region: 'africa',
  },
  moz: {
    flag: 'mz',
    name: 'Mozambique',
    prefix: '+258',
    continent: 'africa',
    region: 'africa',
  },
  nam: {
    flag: 'na',
    name: 'Namibia',
    prefix: '+264',
    continent: 'africa',
    region: 'africa',
  },
  ner: {
    flag: 'ne',
    name: 'Niger',
    prefix: '+227',
    continent: 'africa',
    region: 'africa',
  },
  nga: {
    flag: 'ng',
    name: 'Nigeria',
    prefix: '+234',
    continent: 'africa',
    region: 'africa',
  },
  rwa: {
    flag: 'rw',
    name: 'Rwanda',
    prefix: '+250',
    continent: 'africa',
    region: 'africa',
  },
  stp: {
    flag: 'st',
    name: 'São Tomé and Príncipe',
    prefix: '+239',
    continent: 'africa',
    region: 'africa',
  },
  sen: {
    flag: 'sn',
    name: 'Senegal',
    prefix: '+221',
    continent: 'africa',
    region: 'africa',
  },
  syc: {
    flag: 'sc',
    name: 'Seychelles',
    prefix: '+248',
    continent: 'africa',
    region: 'africa',
  },
  sle: {
    flag: 'sl',
    name: 'Sierra Leone',
    prefix: '+232',
    continent: 'africa',
    region: 'africa',
  },
  som: {
    flag: 'so',
    name: 'Somalia',
    prefix: '+252',
    continent: 'africa',
    region: 'africa',
  },
  zaf: {
    flag: 'za',
    name: 'South africa',
    prefix: '+27',
    continent: 'africa',
    region: 'africa',
  },
  ssd: {
    flag: 'ss',
    name: 'South Sudan',
    prefix: '+211',
    continent: 'africa',
    region: 'africa',
  },
  sdn: {
    flag: 'sd',
    name: 'Sudan',
    prefix: '+249',
    continent: 'africa',
    region: 'africa',
  },
  tza: {
    flag: 'tz',
    name: 'Tanzania',
    prefix: '+255',
    continent: 'africa',
    region: 'africa',
  },
  tgo: {
    flag: 'tg',
    name: 'Togo',
    prefix: '+228',
    continent: 'africa',
    region: 'africa',
  },
  tun: {
    flag: 'tn',
    name: 'Tunisia',
    prefix: '+216',
    continent: 'africa',
    region: 'africa',
  },
  uga: {
    flag: 'ug',
    name: 'Uganda',
    prefix: '+256',
    continent: 'africa',
    region: 'africa',
  },
  esh: {
    flag: 'eh',
    name: 'Western Sahara',
    prefix: '+212',
    continent: 'africa',
    region: 'africa',
  },
  zmb: {
    flag: 'zm',
    name: 'Zambia',
    prefix: '+260',
    continent: 'africa',
    region: 'africa',
  },
  zwe: {
    flag: 'zw',
    name: 'Zimbabwe',
    prefix: '+263',
    continent: 'africa',
    region: 'africa',
  },
} satisfies Record<string, ICountry>;
