import { ICountry } from '@type/word.types';

export const OCEANIA = {
  aus: {
    flag: 'au',
    name: 'Australia',
    prefix: '+61',
    continent: 'oceania',
    region: 'oceania',
  },
  fji: {
    flag: 'fj',
    name: 'Fiji',
    prefix: '+679',
    continent: 'oceania',
    region: 'oceania',
  },
  kir: {
    flag: 'ki',
    name: 'Kiribati',
    prefix: '+686',
    continent: 'oceania',
    region: 'oceania',
  },
  mhl: {
    flag: 'mh',
    name: 'Marshall Islands',
    prefix: '+692',
    continent: 'oceania',
    region: 'oceania',
  },
  mic: {
    flag: 'fm',
    name: 'Micronesia (Federated States of Micronesia)',
    prefix: '+691',
    continent: 'oceania',
    region: 'oceania',
  },
  nru: {
    flag: 'nr',
    name: 'Nauru',
    prefix: '+674',
    continent: 'oceania',
    region: 'oceania',
  },
  nzl: {
    flag: 'nz',
    name: 'New Zealand',
    prefix: '+64',
    continent: 'oceania',
    region: 'oceania',
  },
  plw: {
    flag: 'pw',
    name: 'Palau',
    prefix: '+680',
    continent: 'oceania',
    region: 'oceania',
  },
  png: {
    flag: 'pg',
    name: 'Papua New Guinea',
    prefix: '+675',
    continent: 'oceania',
    region: 'oceania',
  },
  slb: {
    flag: 'sb',
    name: 'Solomon Islands',
    prefix: '+677',
    continent: 'oceania',
    region: 'oceania',
  },
  ton: {
    flag: 'to',
    name: 'Tonga',
    prefix: '+676',
    continent: 'oceania',
    region: 'oceania',
  },
  tuv: {
    flag: 'tv',
    name: 'Tuvalu',
    prefix: '+688',
    continent: 'oceania',
    region: 'oceania',
  },
  vut: {
    flag: 'vu',
    name: 'Vanuatu',
    prefix: '+678',
    continent: 'oceania',
    region: 'oceania',
  },
} satisfies Record<string, ICountry>;
